package com.example.vaersel.ui.home.animation

import com.example.vaersel.R

val animationIconsMap = hashMapOf(
        /* Clothing-icons */
        "jacket_summer_dark" to R.drawable.summer_jacket_dark,
        "jacket_summer_light" to R.drawable.summer_jacket_light,
        "jacket_summer_highcondark" to R.drawable.summer_jacket_highcon,
        "jacket_summer_highconlight" to R.drawable.summer_jacket_highconlight,
        "jacket_fall_dark" to R.drawable.fall_jacket_dark,
        "jacket_fall_light" to R.drawable.fall_jacket_light,
        "jacket_fall_highcondark" to R.drawable.fall_jacket_highcon,
        "jacket_fall_highconlight" to R.drawable.fall_jacket_highconlight,
        "jacket_winter_dark" to R.drawable.winter_jacket_dark,
        "jacket_winter_light" to R.drawable.winter_jacket_light,
        "jacket_winter_highcondark" to R.drawable.winter_jacket_highcon,
        "jacket_winter_highconlight" to R.drawable.winter_jacket_highconlight,
        "jacket_spring_dark" to R.drawable.spring_jacket_dark,
        "jacket_spring_light" to R.drawable.spring_jacket_light,
        "jacket_spring_highcondark" to R.drawable.spring_jacket_highcon,
        "jacket_spring_highconlight" to R.drawable.spring_jacket_highconlight,
        "sweater_summer_dark" to R.drawable.summer_sweater_dark,
        "sweater_summer_light" to R.drawable.summer_sweater_light,
        "sweater_summer_highcondark" to R.drawable.summer_sweater_highcon,
        "sweater_summer_highconlight" to R.drawable.summer_sweater_highconlight,
        "sweater_fall_dark" to R.drawable.fall_sweater_dark,
        "sweater_fall_light" to R.drawable.fall_sweater_light,
        "sweater_fall_highcondark" to R.drawable.fall_sweater_highcon,
        "sweater_fall_highconlight" to R.drawable.fall_sweater_highconlight,
        "sweater_winter_dark" to R.drawable.winter_sweater_dark,
        "sweater_winter_light" to R.drawable.winter_sweater_light,
        "sweater_winter_highcondark" to R.drawable.winter_sweater_highcon,
        "sweater_winter_highconlight" to R.drawable.winter_sweater_highconlight,
        "sweater_spring_dark" to R.drawable.spring_sweater_dark,
        "sweater_spring_light" to R.drawable.spring_sweater_light,
        "sweater_spring_highcondark" to R.drawable.spring_sweater_highcon,
        "sweater_spring_highconlight" to R.drawable.spring_sweater_highconlight,
        "tshirt_summer_dark" to R.drawable.summer_tshirt_dark,
        "tshirt_summer_light" to R.drawable.summer_tshirt_light,
        "tshirt_summer_highcondark" to R.drawable.summer_tshirt_highcon,
        "tshirt_summer_highconlight" to R.drawable.summer_tshirt_highconlight,
        "tshirt_fall_dark" to R.drawable.fall_tshirt_dark,
        "tshirt_fall_light" to R.drawable.fall_tshirt_light,
        "tshirt_fall_highcondark" to R.drawable.fall_tshirt_highcon,
        "tshirt_fall_highconlight" to R.drawable.fall_tshirt_highconlight,
        "tshirt_winter_dark" to R.drawable.winter_tshirt_dark,
        "tshirt_winter_light" to R.drawable.winter_tshirt_light,
        "tshirt_winter_highcondark" to R.drawable.winter_tshirt_highcon,
        "tshirt_winter_highconlight" to R.drawable.winter_tshirt_highconlight,
        "tshirt_spring_dark" to R.drawable.spring_tshirt_dark,
        "tshirt_spring_light" to R.drawable.spring_tshirt_light,
        "tshirt_spring_highcondark" to R.drawable.spring_tshirt_highcon,
        "tshirt_spring_highconlight" to R.drawable.spring_tshirt_highconlight,
        "rainjacket_light" to R.drawable.rainjacket_all,
        "rainjacket_highconlight" to R.drawable.rainjacket_all,
        "rainjacket_dark" to R.drawable.rainjacket_dark,
        "rainjacket_highcondark" to R.drawable.rainjacket_dark,

        /* Leaf-icons */

        "leaf_winter" to R.drawable.winter_leaf,
        "leaf_spring" to R.drawable.spring_leaf,
        "leaf_summer" to R.drawable.summer_leaf,
        "leaf_fall" to R.drawable.fall_leaf,

        "leaf_spring_dark" to R.drawable.spring_leaf_dark,
        "leaf_spring_darkhighcon" to R.drawable.spring_leaf_darkhighcon,
        "leaf_spring_lighthighcon" to R.drawable.spring_leaf_lighthighcon,

        "leaf_summer_dark" to R.drawable.summer_leaf_dark,
        "leaf_summer_darkhighcon" to R.drawable.summer_leaf_darkhighcon,
        "leaf_summer_lighthighcon" to R.drawable.summer_leaf_lighthighcon,

        "leaf_fall_dark" to R.drawable.fall_leaf_dark,
        "leaf_fall_darkhighcon" to R.drawable.fall_leaf_darkhighcon,
        "leaf_fall_lighthighcon" to R.drawable.fall_leaf_lighthighcon,

        "leaf_winter_dark" to R.drawable.winter_leaf_dark,
        "leaf_winter_darkhighcon" to R.drawable.winter_leaf_darkhighcon,
        "leaf_winter_lighthighcon" to R.drawable.winter_leaf_lighthighcon,

        /* Rain-icons */

        "heavy_rain" to R.drawable.much_rain,
        "no_rain" to R.drawable.umbrella_lightmode_lightmodehighcontrast,
        "no_rain_dark" to R.drawable.umbrella_darkmode_darkhighcontrast,
        "no_rain_darkhighcon" to R.drawable.umbrella_darkmode_darkhighcontrast,
        "no_rain_lighthighcon" to R.drawable.umbrella_lightmode_lightmodehighcontrast,
        "rain_dark" to R.drawable.spring_rain_dark,
        "rain_darkhighcon" to R.drawable.spring_rain_darkhighcon,
        "rain_lighthighcon" to R.drawable.spring_rain_lighthighcon,
        "strong_rain_dark" to R.drawable.spring_much_rain_dark,
        "strong_rain_darkhighcon" to R.drawable.spring_much_rain_darkhighcon,
        "strong_rain_lighthighcon" to R.drawable.spring_much_rain_lighthighcon,

        "no_rain_summer_dark" to R.drawable.umbrella_darkmode_darkhighcontrast,
        "no_rain_summer_darkhighcon" to R.drawable.umbrella_darkmode_darkhighcontrast,
        "no_rain_summer_lighthighcon" to R.drawable.umbrella_lightmode_lightmodehighcontrast,
        "rain_summer_dark" to R.drawable.summer_rain_dark,
        "rain_summer_darkhighcon" to R.drawable.summer_rain_darkhighcon,
        "rain_summer_lighthighcon" to R.drawable.summer_rain_lighthighcon,
        "much_rain_summer_dark" to R.drawable.summer_much_rain_dark,
        "much_rain_summer_darkhighcon" to R.drawable.summer_much_rain_darkhighcon,
        "much_rain_summer_lighthighcon" to R.drawable.summer_much_rain_lighthighcon,

        "no_rain_fall_dark" to R.drawable.fall_no_rain_dark,
        "no_rain_fall_darkhighcon" to R.drawable.fall_no_rain_darkhighcon,
        "no_rain_fall_lighthighcon" to R.drawable.fall_no_rain_lighthighcon,
        "rain_fall_dark" to R.drawable.fall_rain_dark,
        "rain_fall_dark_darkhighcon" to R.drawable.fall_rain_darkhighcon,
        "rain_fall_lighthighcon" to R.drawable.fall_rain_lighthighcon,
        "much_rain_fall_dark" to R.drawable.fall_much_rain_dark,
        "much_rain_fall_darkhighcon" to R.drawable.fall_much_rain_darkhighcon,
        "much_rain_fall_lighthighcon" to R.drawable.fall_much_rain_lighthighcon,

        "snowflake" to R.drawable.snowflake,
)

